[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pinker_benchmark"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
authors = [
    {name = "Stéphane Caron", email = "stephane.caron@normalesup.org"},
]
dynamic = ['version', 'description']
requires-python = ">=3.13"
classifiers = [
    "Framework :: Robot Framework :: Library",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "matplotlib",
    "pin-pink ==4.4.0",
    "pink_motions >=0.3.0",
    "pinker ==0.1.0a0",
    "qpmpc >=2.6.3,<4",
    "qpsolvers >=4.3.1",
    "robot_descriptions ==3.0.0",
    "tabulate[widechars] >=0.10.0",
    "xacrodoc",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
pinker_benchmark = { path = ".", editable = true }

[tool.pixi.dependencies]
c-compiler = "*"
clarabel = "*"
daqp = "*"
meshcat-python = "*"
meshcat-shapes = ">=0.3.0"
pinocchio = "==4.1.0"
proxsuite = "*"
pyarrow = "*"
python = "3.13.*"
scipy = "*"

[tool.pixi.tasks]
benchmark = "python -m pinker_benchmark.run"
benchmark-report = "python -m pinker_benchmark.report"
debug-scenario = "python -m pinker_benchmark.debug"

[tool.pixi.feature.lint.dependencies]
ruff = "*"

[tool.pixi.feature.lint.tasks]
dev-format = "ruff format . && ruff check . --fix"
dev-lint = "ruff check ."

[tool.pixi.feature.test.dependencies]
pytest = ">=7.0"

[tool.pixi.feature.test.tasks]
dev-test = "pytest tests/ -v --tb=short"

[tool.pixi.environments]
default = { solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pytest.ini_options]
filterwarnings = ["ignore::qpsolvers.warnings.SparseConversionWarning"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I001",
    # pydocstyle
    "D"
]
ignore = [
    "D401",  # good for methods but not for class docstrings
    "D405",  # British-style section names are also "proper"!
]

[tool.ruff.lint.pydocstyle]
convention = "google"
